---
apiVersion: v2
name: alpine-containerd-toolset
description: alpine-containerd-toolset is lightweight image with containerd compatible tooling
type: application
version: 0.2.1
appVersion: 0.0.1
keywords:
  - containerd
sources:
  - https://github.com/GrabAByte/helm-grababyte-toolset
kubeVersion: '>= 1.24.0-0'
maintainers:
  - name: grababyte
    email: twr.devops@gmail.com
annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/GrabAByte/helm-grababyte-toolset/tree/main/charts/alpine-containerd-toolset
  artifacthub.io/images: |
    - name: alpine-containerd-toolset
      image: alpine-containerd-toolset:0.2.1
